"""subir verdaderas tablas

Revision ID: 87264841b026
Revises:
Create Date: 2025-08-07 19:30:35.755835

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "87264841b026"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categorias",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=60), nullable=True),
        sa.Column("estado", sa.Boolean(), nullable=True),
        sa.Column("fecha_creacion", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "roles",
        sa.Column("id_rol", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=50), nullable=True),
        sa.Column("estado", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id_rol"),
    )
    op.create_table(
        "productos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=60), nullable=True),
        sa.Column("descripcion", sa.String(length=200), nullable=True),
        sa.Column("categoria_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["categoria_id"],
            ["categorias.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "usuarios",
        sa.Column("id_usuario", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=100), nullable=True),
        sa.Column("correo", sa.String(length=100), nullable=True),
        sa.Column("contraseña", sa.String(length=255), nullable=True),
        sa.Column("rol_id", sa.Integer(), nullable=True),
        sa.Column("estado", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["rol_id"],
            ["roles.id_rol"],
        ),
        sa.PrimaryKeyConstraint("id_usuario"),
    )
    op.create_table(
        "chat",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("usuario_origen", sa.Integer(), nullable=True),
        sa.Column("usuario_destino", sa.Integer(), nullable=True),
        sa.Column("mensaje", sa.Text(), nullable=True),
        sa.Column("fecha_envio", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["usuario_destino"],
            ["usuarios.id_usuario"],
        ),
        sa.ForeignKeyConstraint(
            ["usuario_origen"],
            ["usuarios.id_usuario"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "inventarios",
        sa.Column("id_inventario", sa.Integer(), nullable=False),
        sa.Column("producto_id", sa.Integer(), nullable=True),
        sa.Column("cantidad_actual", sa.Integer(), nullable=True),
        sa.Column("fecha_actualizacion", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["producto_id"],
            ["productos.id"],
        ),
        sa.PrimaryKeyConstraint("id_inventario"),
    )
    op.create_table(
        "item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("serial", sa.String(length=60), nullable=True),
        sa.Column("fecha_ingreso", sa.Date(), nullable=True),
        sa.Column("fecha_salida", sa.Date(), nullable=True),
        sa.Column("estado", sa.Boolean(), nullable=True),
        sa.Column("precio", sa.Float(), nullable=True),
        sa.Column("productos_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["productos_id"],
            ["productos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notificaciones",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("usuario_id", sa.Integer(), nullable=True),
        sa.Column("tipo", sa.String(length=50), nullable=True),
        sa.Column("mensaje", sa.Text(), nullable=True),
        sa.Column("fecha_envio", sa.DateTime(), nullable=True),
        sa.Column("estado", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuarios.id_usuario"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pedidos",
        sa.Column("id_pedido", sa.Integer(), nullable=False),
        sa.Column("cliente_id", sa.Integer(), nullable=True),
        sa.Column("fecha_pedido", sa.DateTime(), nullable=True),
        sa.Column("estado", sa.String(length=50), nullable=True),
        sa.Column("total", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["cliente_id"],
            ["usuarios.id_usuario"],
        ),
        sa.PrimaryKeyConstraint("id_pedido"),
    )
    op.create_table(
        "reseñas",
        sa.Column("id_reseña", sa.Integer(), nullable=False),
        sa.Column("producto_id", sa.Integer(), nullable=True),
        sa.Column("cliente_id", sa.Integer(), nullable=True),
        sa.Column("calificación", sa.Integer(), nullable=True),
        sa.Column("comentario", sa.Text(), nullable=True),
        sa.Column("fecha", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["cliente_id"],
            ["usuarios.id_usuario"],
        ),
        sa.ForeignKeyConstraint(
            ["producto_id"],
            ["productos.id"],
        ),
        sa.PrimaryKeyConstraint("id_reseña"),
    )
    op.create_table(
        "videos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("producto_id", sa.Integer(), nullable=True),
        sa.Column("url", sa.String(length=200), nullable=True),
        sa.Column("fecha_subida", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["producto_id"],
            ["productos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "detalle_pedido",
        sa.Column("id_detalle", sa.Integer(), nullable=False),
        sa.Column("pedido_id", sa.Integer(), nullable=True),
        sa.Column("producto_id", sa.Integer(), nullable=True),
        sa.Column("cantidad", sa.Integer(), nullable=True),
        sa.Column("subtotal", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["pedido_id"],
            ["pedidos.id_pedido"],
        ),
        sa.ForeignKeyConstraint(
            ["producto_id"],
            ["productos.id"],
        ),
        sa.PrimaryKeyConstraint("id_detalle"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("detalle_pedido")
    op.drop_table("videos")
    op.drop_table("reseñas")
    op.drop_table("pedidos")
    op.drop_table("notificaciones")
    op.drop_table("item")
    op.drop_table("inventarios")
    op.drop_table("chat")
    op.drop_table("usuarios")
    op.drop_table("productos")
    op.drop_table("roles")
    op.drop_table("categorias")
    # ### end Alembic commands ###
